server:
    port: 9000
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/userdb
        username: root
        password:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
#security:
    #user:
        #name: kingsley
        #password: einstein1998